apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k6z2p1wkr-python-gitops
  description: This is GitOps manifest for k6z2p1wkr-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=k6z2p1wkr-python
    backstage.io/kubernetes-id: k6z2p1wkr-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: k6z2p1wkr-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:k6z2p1wkr-python
